---
name: Search-Indexer-Incremental-MD5
version: 0.01_01
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
abstract: Incrementaly index your files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  BerkeleyDB: 0
  Digest::MD5: 0
  File::Slurp: 0
  List::Util: 0
  Readonly: 0
  Search::Indexer: 0.75
  Sub::Exporter: 0
  Time::HiRes: 0
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Text::Diff: 0
provides:
  Search::Indexer::Incremental::MD5:
    file: lib/Search/Indexer/Incremental/MD5.pm
    version: 0.01_01
  Search::Indexer::Incremental::MD5::Indexer:
    file: lib/Search/Indexer/Incremental/MD5.pm
    version: 0.01
  Search::Indexer::Incremental::MD5::Searcher:
    file: lib/Search/Indexer/Incremental/MD5.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
